name: actions

on: push


jobs:
  test1:
    name: "matplotlib 3.9.1"
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install matplotlib and pyerror
        run: |
          python -m pip install build
          python -m build --wheel
          python -m pip install "matplotlib==3.9.1"
          python -m pip install dist/*.whl
          python -m pip list
      - name: Run tests
        run: |
          python -c "import pyerror; exit(pyerror.test())"

  test2:
    name: "matplotlib 3.9.0"
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install matplotlib and pyerror
        run: |
          python -m pip install build
          python -m build --wheel
          python -m pip install "matplotlib==3.9.0"
          python -m pip install dist/*.whl
          python -m pip list
      - name: Run tests
        run: |
          python -c "import pyerror; exit(pyerror.test())"

  test3:
    name: "matplotlib 3.9.1 from source"
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install matplotlib and pyerror
        run: |
          python -m pip install build
          python -m build --wheel
          python -m pip install --no-binary=matplotlib "matplotlib==3.9.1"
          python -m pip install dist/*.whl
          python -m pip list
      - name: Run tests
        run: |
          python -c "import pyerror; exit(pyerror.test())"
